/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;

/**
 *  Usercode Components
 */
parser code {:
    // Connect this parser to a scanner!
    irScanner s;
    irParser(irScanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};

/**
 *  Symbol Lists
 */


/* Terminals (tokens returned by the scanner). */
terminal            CONCAT, LPAREN, RPAREN, LCBRACKET, RCBRACKET, COMMA,
                    IF, ELSE, REVERSE, PREFIX;
terminal String     STRING_LITERAL, ID;        /*our scanner provides strings*/

/*  Non terminals */
non terminal s, function_decl, function_call, parameters, function_calls, function_decls;
non terminal String     expr ;

/**
 *  Precedence Declarations
 */
precedence left IF, ELSE;
precedence left CONCAT;
precedence left REVERSE;


/**
 *  The Grammar Rules
 */

s ::= function_decls:fd function_calls:fc  {: System.out.println(
    "public class Translated {\n" +  "public static void main(String[] args) {\n"
    + fc + "  }\n"
    + fd +
    "}"); :} ;

function_decls ::=  function_decls:rest function_decl:fd {: RESULT = rest + "\n" + fd; :}
                    |function_decl:fd {: RESULT = fd;:}
                    ;


function_calls ::= function_calls:rest function_call:fc    {: RESULT = rest + "\n" + fc; :}
                | function_call:fc {: RESULT = fc+ "\n"; :}
                ;

expr ::= expr:e1 CONCAT expr:e2  {: RESULT = e1 + " + " + e2; :}
     | STRING_LITERAL:s          {: RESULT = "\"" + s + "\""; :}
     | ID:i                      {: RESULT = i; :}
     ;

function_decl ::= ID:name LPAREN parameters:p RPAREN LCBRACKET
                  expr:body RCBRACKET {: RESULT = "public static String "+ name + "(" + p + ") {\n  return " + body + ";\n}"; :}
                ;


function_call ::= ID:name LPAREN parameters:p RPAREN {: RESULT = name + "(" + p + ");\n"; :};

parameters  ::= expr:p COMMA parameters:rest   {: RESULT = p + ", " + rest; :}
                |expr:p {:RESULT = p;:}
                | {:RESULT = "";:}
                | function_call:fc {:RESULT = fc;:}
                ;
