/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;

/**
 *  Usercode Components
 */
parser code {:
    // Connect this parser to a scanner!
    irScanner s;
    irParser(irScanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};

/**
 *  Symbol Lists
 */


/* Terminals (tokens returned by the scanner). */
terminal            CONCAT_IR, LPAREN_IR, RPAREN_IR, LCBRACKET_IR, RCBRACKET_IR, COMMA_IR,
                    IF_IR, ELSE_IR, REVERSE_IR, PREFIX_IR;
terminal String     STRING_LITERAL_IR, ID_IR;        /*our scanner provides strings*/

/*  Non terminals */
non terminal s, function_decl, parameters, function_calls, function_call,  function_decls, fd_parameters, parameter;
non terminal function_body, if_body;
non terminal String     expr, nested_function_call;

/**
 *  Precedence Declarations
 */
precedence left IF_IR, ELSE_IR;
precedence left CONCAT_IR;
precedence left REVERSE_IR;


/**
 *  The Grammar Rules
 */

s ::= function_decls:fd function_calls:fc  {: System.out.println(
    "public class Translated {\n" +  "    public static void main(String[] args) {\n"
    + fc + "    }\n"
    + fd +
    "\n}") ; :} ;

function_decls ::=  function_decls:rest function_decl:fd {: RESULT = rest + "\n" + fd; :}
                    |function_decl:fd {: RESULT = fd;:}
                    ;

function_decl ::= ID_IR:name LPAREN_IR fd_parameters:p RPAREN_IR LCBRACKET_IR  function_body:body  RCBRACKET_IR 
                {: RESULT = "    public static String "+ name + "(" + p + ") {\n" + body + "\n    }"; :}
                | ID_IR:name LPAREN_IR RPAREN_IR LCBRACKET_IR function_body:body RCBRACKET_IR 
                {: RESULT = "    public static String "+ name + "() {\n" + body + "\n    }"; :}
                ;

fd_parameters ::= fd_parameters:rest COMMA_IR ID_IR:id {: RESULT =  rest + ", " + "String " + id; :}
                  | ID_IR:id    {: RESULT = "String " + id; :}
                  ;

function_calls ::= function_calls:rest function_call:fc {: RESULT = rest + "" + fc; :}
                | function_call:fc {: RESULT = fc; :}
                ;

function_call ::=   ID_IR:name LPAREN_IR parameters:p RPAREN_IR {: RESULT = "        System.out.println(" + name + "(" + p + "));\n"; :}
                    | ID_IR:name LPAREN_IR RPAREN_IR {: RESULT = "        System.out.println(" + name + "());\n"; :}
                    ;

function_body ::= expr:e {: RESULT = "        return "+ e +";"; :}
                | IF_IR LPAREN_IR if_body:b RPAREN_IR function_body:b1 ELSE_IR function_body:b2 
                {: RESULT = "        if (" + b + ") {\n    " + b1 + "\n        } else {\n    " + b2 + "\n        }" ; :}
                ;


if_body ::= expr:id1 PREFIX_IR expr:id2  {:RESULT = id1 + ".startsWith(" + id2 + ")";:}
            ;


expr ::= expr:e1 CONCAT_IR expr:e2  {: RESULT = e1 + " + " + e2; :}
     | STRING_LITERAL_IR:s          {: RESULT = "\"" + s + "\""; :}
     | ID_IR:var                      {: RESULT = var; :}
     | nested_function_call:fc {: RESULT = fc; :}
     | REVERSE_IR expr:e   {: RESULT = "new StringBuilder(" + e + ").reverse().toString()"; :}
     ;

parameters ::= parameters:rest COMMA_IR parameter:p {: RESULT = rest + ", " + p; :}
             | parameter:p {: RESULT = p; :}
             ;

parameter ::= STRING_LITERAL_IR:sl {: RESULT = "\"" + sl + "\""; :}
            | nested_function_call:fc {: RESULT = fc; :}
            ;

nested_function_call ::=   ID_IR:name LPAREN_IR parameters:p RPAREN_IR {: RESULT = name + "(" + p + ")"; :}
                    | ID_IR:name LPAREN_IR RPAREN_IR {: RESULT = name + "()"; :}
                    ;
