/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;

/**
 *  Usercode Components
 */
parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};

/**
 *  Symbol Lists
 */

/* Terminals (tokens returned by the scanner). */
terminal            CONCAT, LPAREN, RPAREN, LCBRACKET, RCBRACKET, COMMA,
                    IF, ELSE, REVERSE, PREFIX;   //, SUFFIX, EQUAL;
terminal String     STRING_LITERAL;        /*our scanner provides strings*/
terminal String     ID;

/*  Non terminals */
non terminal s, function_decl, function_call, parameters, program;
non terminal String     expr ;

/**
 *  Precedence Declarations
 */
precedence left IF, ELSE;
precedence left CONCAT;
precedence left REVERSE;

/**
 *  The Grammar Rules
 */

s ::= program   {: System.out.println(RESULT); :}   ;

program ::= function_decl:fd s:rest    {: RESULT = fd + "\n" + rest; :}
            |  function_decl:fd            {: RESULT = fd; :}
            |  function_call:fc s:rest     {: RESULT = fc + "\n" + rest; :}
            |  function_call:fc            {: RESULT = fc; :}
            ;


expr ::= expr:e1 CONCAT expr:e2  {: RESULT = e1 + " + " + e2; :}
     | STRING_LITERAL:s          {: RESULT = "\"" + s + "\""; :}
     | ID:i                      {: RESULT = i; :}
     ;

function_decl ::= ID:name LPAREN parameters:p RPAREN LCBRACKET
                  ID:body RCBRACKET {: RESULT = name + "(" + p + ") {\n  " + body + "\n}"; :}
                ;

function_call ::= ID:name LPAREN parameters:p RPAREN {: RESULT = name + "(" + p + ")"; :};

parameters  ::= expr:p COMMA parameters:rest   {: RESULT = p + ", " + rest; :}
                |expr:p {:RESULT = p;:}
                | {:RESULT = "";:}
                ;
