/* Simple +/-/* expression language; parser evaluates constant expressions on the fly*/
/**
 *  Package and Import Specifications
 */
import java_cup.runtime.*;

/**
 *  Usercode Components
 */
parser code {:
    // Connect this parser to a scanner!
    Scanner s;
    Parser(Scanner s){ this.s=s; }
:}

/* define how to connect to the scanner! */
scan with {: return s.next_token(); :};

/**
 *  Symbol Lists
 */

/* Terminals (tokens returned by the scanner). */
terminal            CONCAT, LPAREN, RPAREN, LCBRACKET, RCBRACKET, COMMA,
                    IF, ELSE, REVERSE, PREFIX, SUFFIX, EQUAL;
terminal String     STRING_LITERAL;        /*our scanner provides strings*/
terminal String     ID;


/* Non-terminals */
non terminal s, function_decl, parameters, function_calls, function_decls, fd_parameters;
non terminal function_body, function_call, if_body;
non terminal String expr, nested_function_call;

/**
 *  Precedence Declarations
 */
precedence left IF, ELSE;
precedence left CONCAT;
precedence left REVERSE;


/* The Grammar Rules (modified actions) */
s ::= function_decls:fd function_calls:fc {: System.out.println(fd); System.out.println(fc); :} ;

function_decls ::= function_decls:rest function_decl:fd {: RESULT = rest + "\n" + fd; :}
                  | function_decl:fd {: RESULT = fd; :} ;

function_decl ::= ID:name LPAREN fd_parameters:p RPAREN LCBRACKET function_body:body RCBRACKET 
                {: RESULT = name + "(" + p + ") { \n    " + body + "\n} \n"; :}
                | ID:name LPAREN RPAREN LCBRACKET function_body:body RCBRACKET 
                {: RESULT = name + "() { \n    " + body + "\n} \n"; :} ;

fd_parameters ::= fd_parameters:rest COMMA ID:id {: RESULT = rest + ", " + id; :}
                 | ID:id {: RESULT = id; :} ;

function_calls ::= function_calls:rest function_call:fc {: RESULT = rest +  "\n" + fc; :}
                 | function_call:fc {: RESULT = fc; :} ;

function_call ::= ID:name LPAREN parameters:p RPAREN {: RESULT = name + "(" + p + ")\n"; :}
                 | ID:name LPAREN RPAREN {: RESULT = name + "()\n"; :} ;

function_body ::= expr:e {: RESULT = e; :}
                | IF LPAREN expr:e1 PREFIX expr:e2 RPAREN function_body:b1 ELSE function_body:b2 
                {: RESULT = "if (" + e1 + " prefix " + e2 + ")\n        " + b1 + "\n     else\n        " + b2; :}
                | IF LPAREN expr:e1 SUFFIX expr:e2 RPAREN function_body:b1 ELSE function_body:b2 
                {: RESULT = "if (" + "reverse " + e1 + " prefix reverse " + e2 + ")\n        " + b1 + "\n     else\n        " + b2; :}
                | IF LPAREN expr:e1 EQUAL expr:e2 RPAREN function_body:b1 ELSE function_body:b2 
                {: RESULT = "if (" + e1 + " prefix " + e2 + ")\n        " + "if (" + e2 + " prefix " + e1 + ")\n        "
                 + b1 + "\n     else\n        " + b2 + "\n     else\n        " + b2; :}
                ;

expr ::= expr:e1 CONCAT expr:e2 {: RESULT = e1 + "+" + e2; :}
       | STRING_LITERAL:s {: RESULT = "\"" + s + "\""; :}
       | ID:var {: RESULT = var; :}
       | nested_function_call:fc {: RESULT = fc; :}
       | REVERSE expr:e {: RESULT = "reverse " + e; :}
        ;

parameters ::= parameters:rest COMMA expr:p {: RESULT = rest + ", " + p; :}
             | expr:p {: RESULT = p; :} ;


nested_function_call ::= ID:name LPAREN parameters:p RPAREN {: RESULT = name + "(" + p + ")"; :}
                       | ID:name LPAREN RPAREN {: RESULT = name + "()"; :} ;